# Generated by Django 4.2.20 on 2025-04-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
    ]
