# Generated by Django 4.2.20 on 2025-04-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_business_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='num_empleados',
            field=models.IntegerField(default=0),
        ),
    ]
