# Generated by Django 4.2.20 on 2025-04-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_business_num_empleados'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
