# Generated by Django 4.2.20 on 2025-04-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_business_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/'),
        ),
    ]
